import {Model, model, models, ObjectId, Schema} from "mongoose";

interface autoPlayListDocument {
  title: string;
  items: ObjectId[];
}

const playlistSchema = new Schema<autoPlayListDocument>(
  {
    title: {
      type: String,
      required: true,
    },

    items: [
      {
        type: Schema.Types.ObjectId,
        required: true,
        ref: "Audio",
      },
    ],
  },
  {timestamps: true}
);

const AutoGeneratedPlayList = models.AutoGeneratedPlayList || model("AutoGeneratedPlayList", playlistSchema);

export default AutoGeneratedPlayList as Model<autoPlayListDocument>;
