import {
  getAutoGeneratedPlayList,
  getFollowerProfile,
  getFollowerProfilePublic,
  getFollowingsProfile,
  getIsFollowing,
  getPlayListAudios,
  getPrivatePlaylistAudios,
  getPublicPlaylist,
  getPublicProfile,
  getPublicUploads,
  getRecommendByProfile,
  getUploads,
  updateFollower,
} from "#/controllers/profile";
import {isAuth, mustAuth} from "#/middleware/auth";
import {Router} from "express";

const router = Router();
router.post("/update-follower/:profileId", mustAuth, updateFollower);
router.get("/uploads", mustAuth, getUploads);
router.get("/uploads/:profileId", getPublicUploads);
router.get("/info/:profileId", getPublicProfile);
router.get("/playlist/:profileId", getPublicPlaylist);
router.get("/recommended", isAuth, getRecommendByProfile);
router.get("/auto-generated-playlist", mustAuth, getAutoGeneratedPlayList);
router.get("/followers", mustAuth, getFollowerProfile);
router.get("/followers/:profileId", mustAuth, getFollowerProfilePublic);
router.get("/followings", mustAuth, getFollowingsProfile);
router.get("/playlist-audios/:playlistId", getPlayListAudios);
router.get("/private-playlist-audios/:playlistId", mustAuth, getPrivatePlaylistAudios);
router.get("/is-following/:profileId", mustAuth, getIsFollowing);

export default router;
